ImmobilienViewer/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import *

router = DefaultRouter()
router.register('immobilie', ImmobilienAPIView)

app_name = 'immoviewer'

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html", extra_context = {'active': 'home'}), name="homepage"),
    path('immobilie/detail/<uuid:uuid>/', ImmobilienDetailView.as_view(), name="immo-detail"),
    path('immobilie/list/', ImmobilienListView.as_view(), name='immo-list'),
    path('immobilie/list/<slug:tag_slug>/', TaggedImmobilienListView.as_view(), name='immo-tagged-list'),
    path('region/create/', CreateRegionView.as_view(), name='immo-create-region'),
    path('immobilie/create', CreateImmobilieView.as_view(), name='immo-create-immobilie'),
    path('immobilie/update/<uuid:uuid>/', UpdateImmobilieView.as_view(), name='immo-update-immobilie'),
    path('immobilie/delete/<uuid:uuid>/', DeleteImmobilieView.as_view(), name='immo-delete-immobilie'),
    path('immobilie/attachments/list/<uuid:uuid>/', AttachmentListView.as_view(), name='immo-list-attachments'),
    path('immobilie/attachment/upload/<uuid:uuid>/', UploadAttachmentView.as_view(), name='immo-upload-attachment'),
    path('immobilie/attachment/delete/<uuid:uuid>/', DeleteAttachmentView.as_view(), name='immo-delete-attachment'),
    path('list-by-region/<uuid:uuid>/', RegionListView.as_view(), name='immo-list-by-region'),
    path('map/', MapView.as_view(), name='immo-map'),
    path('immobilie/tag/', tag_immobilie, name='tag-immo'),
    path('api/', include(router.urls)),
    path('api/geojson/list/', GeoJSONAPIView.as_view(), name='api-geojson-list')
]

core/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from ImmobilienViewer.views import ImmoSearchView

urlpatterns = [
    path('',  RedirectView.as_view(pattern_name='immoviewer:homepage', permanent=False)),
    path('admin/', admin.site.urls),
    path('immoviewer/', include('ImmobilienViewer.urls', namespace='immoviewer')),
    path('search/', ImmoSearchView.as_view(), name='haystack-search'),

]

if settings.DEBUG:
    # Todo fix for production mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

ImmobilienViewer/forms.py
from django import forms

from core.models import Region, Immobilie, FileAttachment, District


class AddRegionForm(forms.ModelForm):

    class Meta:
        model = Region
        exclude = ['uuid']

    name = forms.CharField(widget=forms.TextInput())
    districts = forms.ModelMultipleChoiceField(
        widget=forms.SelectMultiple(attrs={'id': 'district-selection'}),
        queryset=District.objects.all()
        )


class ImmobilieForm(forms.ModelForm):

    class Meta:
        model = Immobilie
        fields = ('title', 'description', 'provider','provider_id', 'price', 'url', 'location')


class AttachmentForm(forms.ModelForm):

    class Meta:
        model = FileAttachment
        fields = ('name', 'attachment')

ImmobilienViewer/views.py
from django.core.serializers import serialize
from django.db.models.query import EmptyQuerySet
from django.http import JsonResponse, Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, TemplateView
from haystack.forms import SearchForm
from haystack.generic_views import SearchView
from rest_framework import viewsets, generics

from django.contrib import messages
from rest_framework.generics import ListAPIView
from rest_framework.status import HTTP_405_METHOD_NOT_ALLOWED, HTTP_400_BAD_REQUEST

from ImmobilienViewer import serializers
from ImmobilienViewer.forms import AddRegionForm, ImmobilieForm, AttachmentForm
from core.models import Immobilie, Region, FileAttachment
from taggit.models import Tag


class ImmobilienDetailView(DetailView):

    model = Immobilie
    template_name = 'immo_detail.html'
    context_object_name = 'immobilie'

    def get_object(self, *args, **kwargs):
        immo = Immobilie.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        return immo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        immo = Immobilie.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        context['alltags'] = Tag.objects.all()
        context['attachments'] = immo.attachments.all()
        context['immotags'] = immo.tags.all()
        return context

class ImmobilienListView(ListView):

    model = Immobilie
    template_name = "immo_list.html"
    context_object_name = 'immobilien'
    paginate_by = 9
    queryset = Immobilie.objects.filter(deleted=False).order_by('-location')
    extra_context = {'active': 'list', 'tags': Tag.objects.all()}


class TaggedImmobilienListView(ListView):

    model = Immobilie
    template_name = "immo_tagged_list.html"
    context_object_name = 'immobilien'
    paginate_by = 9

    def get_queryset(self):
        return Immobilie.objects.filter(deleted=False).filter(tags__slug=self.kwargs.get('tag_slug')).order_by('-location')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active'] = 'list'
        context['tags'] = Tag.objects.all()
        context['tag_slug'] = self.kwargs.get('tag_slug')
        return context

class RegionListView(ListView):

    model = Immobilie
    template_name = "immo_list.html"
    context_object_name = 'immobilien'
    paginate_by = 1
    extra_context = {'active': 'list-by-region'}

    def get_queryset(self, *args, **kwargs):
        region_result = Region.objects.filter(uuid=self.kwargs.get('uuid'))
        if len(region_result) > 0:
            return Immobilie.objects.filter(region=region_result[0])
        else:
            return EmptyQuerySet()

class CreateRegionView(CreateView):

    model = Region
    form_class = AddRegionForm
    template_name = 'forms/region_form.html'
    extra_context = {'title': 'Create a new region', 'active': 'create'}

    def get_success_url(self):
        return reverse('immoviewer:immo-list')

class CreateImmobilieView(CreateView):

    model = Immobilie
    form_class = ImmobilieForm
    template_name = 'forms/immobilie_form.html'
    extra_context = {'title': 'Create a new Immobilie', 'active': 'create'}

    def get_success_url(self):
        return reverse('immoviewer:immo-list')

class UpdateImmobilieView(UpdateView):

    model = Immobilie
    form_class = ImmobilieForm
    template_name = 'forms/immobilie_form.html'
    extra_context = {'title': 'Update existing Immobilie', 'active': 'edit'}

    def get_success_url(self):
        url = reverse('immoviewer:immo-detail', kwargs={'uuid': self.kwargs['uuid']})
        return url

    def get_object(self, *args, **kwargs):
        return Immobilie.objects.filter(uuid=self.kwargs.get('uuid'))[0]

    def form_valid(self, form):
        messages.success(self.request, "The immobilie was updated successfully.")
        return super(UpdateImmobilieView,self).form_valid(form)


class DeleteImmobilieView(DeleteView):

    model = Immobilie
    context_object_name = 'immobilie'
    template_name = 'forms/immobilie_confirm_delete_form.html'

    def get_object(self, *args, **kwargs):
        return Immobilie.objects.filter(uuid=self.kwargs.get('uuid'))[0]

    def get_success_url(self):
        return reverse('immoviewer:immo-list')

    def form_valid(self, form):
        messages.success(self.request, "The task was deleted successfully.")
        return super(DeleteImmobilieView,self).form_valid(form)



class UploadAttachmentView(CreateView):

    model = FileAttachment
    form_class = AttachmentForm
    template_name = 'forms/upload_form.html'

    def get_success_url(self):
        url = reverse('immoviewer:immo-list-attachments', kwargs={'uuid': self.kwargs['uuid']})
        return url

    def form_valid(self, form):
        immobilie = Immobilie.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        form.instance.immobilie = immobilie
        return super().form_valid(form)

class AttachmentListView(ListView):

    model = FileAttachment
    template_name = 'attachment_list.html'
    context_object_name = 'attachments'

    def get_queryset(self):
        attachments =  FileAttachment.objects.filter(immobilie__uuid=self.kwargs.get('uuid'))
        return attachments

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        immobilie =  Immobilie.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        context['immobilie'] = immobilie
        return context

class DeleteAttachmentView(DeleteView):

    model = FileAttachment
    template_name = 'forms/attachment_confirm_delete.html'
    context_object_name = 'attachment'

    def get_queryset(self):
        attachments = FileAttachment.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        return attachments

    def form_valid(self, form):
        messages.success(self.request, "The attachment was deleted successfully.")
        return super(DeleteAttachmentView,self).form_valid(form)

    def get_object(self, *args, **kwargs):
        attachments = FileAttachment.objects.filter(uuid=self.kwargs.get('uuid'))
        return attachments

    def get_success_url(self):
        attachment = FileAttachment.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        url = reverse('immoviewer:immo-list-attachments', kwargs={'uuid': attachment.immobilie.uuid})
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        attachment = FileAttachment.objects.filter(uuid=self.kwargs.get('uuid'))[0]
        context['immobilie'] = attachment.immobilie
        return context

class ImmoSearchView(SearchView):

    template_name = 'search/search.html'
    form_class = SearchForm

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context


class MapView(TemplateView):

    template_name = 'map.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        geojson = serialize("geojson", Immobilie.objects.filter(map_location__isnull=False), geometry_field="map_location", fields=["title", "location"])

        return context


class ImmobilienAPIView(viewsets.ModelViewSet):

    serializer_class = serializers.ImmobilienSerializer
    queryset = Immobilie.objects.all()


class GeoJSONAPIView(ListAPIView):

    queryset = Immobilie.objects.filter(map_location__isnull=False)
    serializer_class = serializers.ImmobilieLocationSerializer

def remove_all_tags_without_objects():
    for tag in Tag.objects.all():
        if tag.taggit_taggeditem_items.count() == 0:
            print('Removing: {}'.format(tag))
            tag.delete()
        else:
            print('Keeping: {}'.format(tag))



def tag_immobilie(request):
    if request.POST.get('action') == 'post':
        if request.POST.get('tagaction') == "add":
            immobilie_uuid = request.POST.get('immobilie')
            tagname = request.POST.get('tagname')
            immobilie = Immobilie.objects.filter(uuid=immobilie_uuid)[0]
            immobilie.tags.add(tagname)
            immobilie._meta.auto_created = True
            immobilie.save()
            immobilie._meta.auto_created = False
            return JsonResponse({'result': tagname})
        elif request.POST.get('tagaction') == "remove":
            immobilie_uuid = request.POST.get('immobilie')
            tagname = request.POST.get('tagname')
            immobilie = Immobilie.objects.filter(uuid=immobilie_uuid)[0]
            immobilie.tags.remove(tagname)
            immobilie._meta.auto_created = True
            immobilie.save()
            immobilie._meta.auto_created = False
            remove_all_tags_without_objects()
            return JsonResponse({'result': tagname})
        else:
            return HttpResponse(status=HTTP_400_BAD_REQUEST)
    else:
        return HttpResponse(status=HTTP_405_METHOD_NOT_ALLOWED)

ImmobilienViewer/templates/attachment_list.html
{% extends "base.html" %}

{% block title %}Attachment list{% endblock %}

{% block content %}
    <div class="container">

        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Attachments for {{attachments.0.immobilie.title}}</h1>
            <p class="lead">List of attachments</p>
        </div>
         <a class="btn btn-secondary" href="{% url 'immoviewer:immo-detail' immobilie.uuid %}" role="button">Back to immobilie</a>
         <a class="btn btn-secondary" href="{% url 'immoviewer:immo-upload-attachment' immobilie.uuid %}" role="button">Upload attachments</a>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">File</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
             {% for attachment in attachments %}
                <tr>
                  <td>{{attachment.name}}</td>
                  <td>{{attachment.attachment.url}}</td>
                  <td><a class="btn btn-danger" href="{% url 'immoviewer:immo-delete-attachment' attachment.uuid %}" role="button">Delete</a></td>
                </tr>
             {% endfor %}
          </tbody>
        </table>
    </div>

{% endblock %}

ImmobilienViewer/templates/base.html
<!DOCTYPE html>
<head>

  {# Load the tag library #}
  {% load django_bootstrap5 %}
  {% bootstrap_css %}

  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
      integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
      crossorigin=""/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
   {% block css %}{% endblock css %}
</head>
<html>
<body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'immoviewer:homepage' %}">ImmobilienViewer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">

              <a class="nav-link {% if active == 'home' %}active{% endif %}" aria-current="page" href="{% url 'immoviewer:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if active == 'list' %}active{% endif %}" href="{% url 'immoviewer:immo-list' %}">List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if active == 'map' %}active{% endif %}" href="{% url 'immoviewer:immo-map' %}">Map</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link {% if active == 'list-by-region' %}active{% endif %} dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                List by region
              </a>
              <ul class="dropdown-menu">
                {% for region in regionen %}
                <li><a class="dropdown-item" href="{% url 'immoviewer:immo-list-by-region' uuid=region.uuid %}">{{region.name}}</a></li>
                {% endfor %}
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link {% if active == 'create' %}active{% endif %} dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Create
              </a>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'immoviewer:immo-create-region' %}">Region</a></li>
                <li><a class="dropdown-item" href="{% url 'immoviewer:immo-create-immobilie' %}">Immobilie</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search" id="searchform">
            <input class="form-control me-2" id="searchinput" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </ul>
      </div>
    </nav>

 {% block content %}{% endblock content %}
  {# Load CSS and JavaScript #}

  {% bootstrap_javascript %}

  {# Display django.contrib.messages as Bootstrap alerts #}
  {% bootstrap_messages %}

  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
  integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
  crossorigin=""></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
  integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  {% block js %}{% endblock js %}
  <script>
       document.getElementById('searchform').addEventListener('submit', function(event) {
          event.preventDefault();

          let baseUrl = '{% url 'haystack-search' %}';
          let query = document.getElementById('searchinput').value;
          if (query) {
              let fullUrl = `${baseUrl}?q=${encodeURIComponent(query)}`;
              window.location.href = fullUrl;
          }
       });
  </script>
</body>
</html>

ImmobilienViewer/templates/create.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{title}}</h1>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ImmobilienViewer/templates/immo_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Immobilie{% endblock %}

{% block css %}
  <link
  rel="stylesheet"
  href="{% static 'map.css' %}"/>
{% endblock css %}


{% block content %}
<div class="container my-5">
    <a class="btn btn-primary" href="{% url 'immoviewer:immo-update-immobilie' immobilie.uuid %}" role="button">Edit</a>
    <a class="btn btn-secondary" href="{% url 'immoviewer:immo-upload-attachment' immobilie.uuid %}" role="button">Upload attachments</a>
    {% if attachments|length > 0 %}
    <a class="btn btn-secondary" href="{% url 'immoviewer:immo-list-attachments' immobilie.uuid %}" role="button">List attachments</a>
    {% endif %}
    <a class="btn btn-danger" href="{% url 'immoviewer:immo-delete-immobilie' immobilie.uuid %}" role="button">Delete</a>
    <div class="my-5">
        {% csrf_token %}
        <select class="form-control" id="tags-selection"  multiple="multiple">

            {% for tag in alltags %}
                {% if tag in immotags %}
                    <option value="{{ tag.id }}" selected="selected">{{ tag.name }}</option>
                {% else %}
                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endif %}
            {% endfor %}

        </select>

    </div>

  <div class="p-5 text-left bg-body-tertiary rounded-3">
    <h1 class="text-body-emphasis text-center">{{immobilie.title}}</h1>
    <p class="col-lg-8 mx-auto fs-5 text-muted">{{immobilie.description}}</p>
    <ul>
        <li><small class="text-muted">Type: {{immobilie.type}}</small></li>
        <li><small class="text-muted">Price: {{immobilie.price}}</small></li>
        <li><small class="text-muted">Provider: {{immobilie.provider}}</small></li>
        <li><small class="text-muted">Location: {{immobilie.location}}</small></li>
    </ul>
        <p class="text-body-emphasis text-left">Attachments</p>
      <ul>
   {% for attachment in attachments %}
            <li><a href="{{ attachment.attachment.url }}">{{ attachment.name }}</a></li>
    {% endfor %}
      </ul>
  </div>
</div>
{% if immobilie.lat_lng|length > 0 %}
    <div class="container-lg my-5 bg-body-tertiary rounded-3" id="map">
            <script>
                var mapLatitudeLongitude = {{immobilie.lat_lng}};
                var mapAdress = "{{immobilie.location}}";
            </script>
            <script defer src="{% static 'map_marker.js' %}"></script>
    </div>

{% endif %}

{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
    $('#tags-selection').select2({
        tags: true,
        tokenSeparators: [",", " "],
        createTag: function (tag) {
            return {
                id: tag.term,
                text: tag.term,
                isNew : true
            };
        }
    }).on("select2:select", function(e) {
        if(e.params.data.isNew){
            console.log("New tag: " + e.params.data.id + ":" + e.params.data.text);
            $.ajax({
                  type: 'POST',
                  url: '{% url "immoviewer:tag-immo" %}',
                  data: {
                    immobilie: "{{ immobilie.uuid }}",
                    tagname: e.params.data.text,
                    tagaction: "add",
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                  },
                  success: function (json) {
                    console.log("Success: " + json);
                  },
                  error: function (xhr, errmsg, err) {
                    console.log("Error: " + errmsg);
                  }
                });
            //$(this).find('[value="'+e.params.data.id+'"]').replaceWith('<option selected value="'+e.params.data.id+'">'+e.params.data.text+'</option>');
        }
    }).on("select2:unselecting", function(e) {
        console.log("Unselecting " + e.params.args.data.id + " : " + e.params.args.data.text);
            $.ajax({
                  type: 'POST',
                  url: '{% url "immoviewer:tag-immo" %}',
                  data: {
                    immobilie: "{{ immobilie.uuid }}",
                    tagname: e.params.args.data.text,
                    tagaction: "remove",
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                  },
                  success: function (json) {
                    console.log("Success: " + json);
                  },
                  error: function (xhr, errmsg, err) {
                    console.log("Error: " + errmsg);
                  }
                });
    });

});
</script>
{% endblock js %}

ImmobilienViewer/templates/immo_list.html
{% extends "base.html" %}

{% block title %}Immobilienliste{% endblock %}

{% block content %}

    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Alle Immobilien</h1>
            <p class="lead">List of saved plot and house offers</p>
        </div>
        <div class="py-5">
            <div class="row">
                {% for immobilie in immobilien %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'immoviewer:immo-detail' immobilie.uuid %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{immobilie.title|truncatechars:50}}</h2>
                                <ul>
                                    <li><small class="text-muted">Type: {{immobilie.type}}</small></li>
                                    <li><small class="text-muted">Price: {{immobilie.price}}</small></li>
                                    <li><small class="text-muted">Provider: {{immobilie.provider}}</small></li>
                                    <li><small class="text-muted">Location: {{immobilie.location}}</small></li>
                                </ul>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ImmobilienViewer/templates/immo_tagged_list.html
{% extends "base.html" %}

{% block title %}Immobilienliste{% endblock %}

{% block content %}

    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Alle Immobilien</h1>
            <p class="lead">List of saved plot and house offers</p>
            <div class="my-5">
                {% for tag in tags %}
                    {% if tag.slug == tag_slug %}
                        <a href="{% url 'immoviewer:immo-tagged-list' tag.slug %}" class="btn btn-secondary">{{ tag.name }}</a>
                    {% else %}
                        <a href="{% url 'immoviewer:immo-tagged-list' tag.slug %}" class="btn btn-outline-secondary">{{ tag.name }}</a>
                    {% endif %}
                {% empty %}
                    <p>No tags</p>
                {% endfor %}
                <a href="{% url 'immoviewer:immo-list' %}" class="btn btn-primary">All</a>
            </div>
        </div>
        <div class="py-5">
            <div class="row">
                {% for immobilie in immobilien %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'immoviewer:immo-detail' immobilie.uuid %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{immobilie.title|truncatechars:50}}</h2>
                                <ul>
                                    <li><small class="text-muted">Type: {{immobilie.type}}</small></li>
                                    <li><small class="text-muted">Price: {{immobilie.price}}</small></li>
                                    <li><small class="text-muted">Provider: {{immobilie.provider}}</small></li>
                                    <li><small class="text-muted">Location: {{immobilie.location}}</small></li>
                                </ul>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ImmobilienViewer/templates/index.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <h1>Hello World!</h1>
    <p>Welcome to my first Django project!</p>
{% endblock %}